import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { Footer } from "@/components/shared/Footer";
import { Header } from "@/components/shared/Header";
import { Providers } from "@/modules/shared";

// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
// })

const local = localFont({
  src: [
    {
      path: './fonts/Dune_Rise.ttf',
      weight: '400 700',
      style: 'normal',
    },
    {
      path: './fonts/Dune_Rise.otf',
      weight: '400 700',
      style: 'normal',
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${local.className} dark antialiased`}
      >
        <Providers>
          <Header />
          <main className="overflow-hidden">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
